version: '3'

services:
  postgres:
    image: ankane/pgvector
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
